//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _50DersMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Satislar
    {
        public int satısID { get; set; }
        public Nullable<int> ürünID { get; set; }
        public Nullable<int> müsteriID { get; set; }
        public Nullable<byte> Adet { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    
        public virtual tbl_Müsteriler tbl_Müsteriler { get; set; }
        public virtual tbl_Ürünler tbl_Ürünler { get; set; }
    }
}
