//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _50DersMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kategoriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Kategoriler()
        {
            this.tbl_Ürünler = new HashSet<tbl_Ürünler>();
        }
    
        public short kategoriID { get; set; }
        public string kategoriAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ürünler> tbl_Ürünler { get; set; }
    }
}
