//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _50DersMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Müsteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Müsteriler()
        {
            this.tbl_Satislar = new HashSet<tbl_Satislar>();
        }
    
        public int müsteriID { get; set; }
        public string müsteriAD { get; set; }
        public string müsteriSOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Satislar> tbl_Satislar { get; set; }
    }
}
