//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _50DersMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ürünler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Ürünler()
        {
            this.tbl_Satislar = new HashSet<tbl_Satislar>();
        }
    
        public int ürünID { get; set; }
        public string ürünAD { get; set; }
        public Nullable<short> ürünKATEGORİ { get; set; }
        public Nullable<decimal> ürünFİYAT { get; set; }
        public string Marka { get; set; }
        public Nullable<byte> Stok { get; set; }
    
        public virtual tbl_Kategoriler tbl_Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Satislar> tbl_Satislar { get; set; }
    }
}
